name: Verificar Estabilidad del Sitio Web

on:
  schedule:
    - cron: '0 10 * * *'  # Ejecuta el trabajo a las 10 AM UTC

jobs:
  check-site:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permite que las acciones escriban en el repositorio

    steps:
      - uses: actions/checkout@v2
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Ejecutar script
        run: python sec_scripts/security.py
      - name: Configurar Git
        run: |
          git config --global user.name 'edujbarrios'
          git config --global user.email 'eduardojbarriosgarcia@gmail.com'
      - name: Hacer commit de los cambios
        run: |
          git add checks/log.csv
          git commit -m "Security checks completed and page running"
          git push || echo "No changes to commit or push failed"

